language : cpp
dist: trusty
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
    - valgrind
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - (cd logger;npm install)
    - sh -e /etc/init.d/xvfb start
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - wget https://download.qt.io/archive/online_installers/3.0/qt-unified-linux-x64-3.0.1-online.run
    - QT_CI_PACKAGES="preview.qt.qt5.510.gcc_64" extract-qt-installer qt-unified-linux-x64-3.0.1-online.run `pwd`/Qt
    - node logger/create.js Qt/components "Qt 5.10" preview.qt.qt5.5100.gcc_64
    - QT_HOME=$PWD/`find Qt -name gcc_64`
    - echo $QT_HOME
    - export PATH=${QT_HOME}/bin:$PATH
    - which qmake
    - qmake --version
    - git clone https://github.com/benlau/qredux.git
    - ./test.sh `pwd`/qredux/tests/qreduxtests/qreduxtests.pro
    - git clone https://github.com/benlau/asyncfuture.git
    - ./test.sh `pwd`/asyncfuture/tests/asyncfutureunittests/asyncfutureunittests.pro
    - git clone https://github.com/benlau/quickflux.git
    - ./test.sh $PWD/`find quickflux/tests -name *.pro`
    - git clone https://github.com/benlau/sparkqml.git
    - ./test.sh $PWD/`find sparkqml/tests/sparkqmltests -name *.pro`
    - ./test.sh $PWD/qtbug-62666/qtbug-62666.pro

