language : cpp
dist: trusty
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
    - valgrind
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - find $GOPATH
    - sh -e /etc/init.d/xvfb start
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - wget https://download.qt.io/archive/online_installers/2.0/qt-unified-linux-x64-2.0.5-online.run
    - VERBOSE=true QT_CI_PACKAGES="qt.59.gcc_64" extract-qt-installer qt-unified-linux-x64-2.0.5-online.run `pwd`/Qt
    - ls Qt
    - QT_HOME=`find Qt -name gcc_64`
    - echo $QT_HOME
    - export PATH=$QT_HOME:$PATH
    - git clone https://github.com/benlau/qredux.git
    - ./test.sh `pwd`/qredux/tests/qreduxtests/qreduxtests.pro
    - git clone https://github.com/benlau/asyncfuture.git
    - ./test.sh `pwd`/asyncfuture/tests/asyncfutureunittests/asyncfutureunittests.pro

