language : cpp
dist: trusty
env:
  - DISPLAY=:99.0 TARGET_NAME="Qt 5.9.2" TARGET_PACKAGE="qt.592.gcc_64"
addons:
  apt:
    packages:
    - valgrind
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - (cd logger;npm install)
    - sh -e /etc/init.d/xvfb start
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - install-qt-5.9.2 
    - source qt-5.9.2.env
    - ls Qt
    - find Qt -name "qmake"
    - echo $PATH
    - node logger/create.js $PWD/Qt/components.xml "${TARGET_NAME}" "${TARGET_PACKAGE}"
    - which qmake
    - qmake --version
    - ./run-test.sh "QTBUG-62666" $PWD/qtbug-62666/qtbug-62666.pro
    #- git clone https://github.com/benlau/qredux.git
    #- ./run-test.sh "QRedux" `pwd`/qredux/tests/qreduxtests/qreduxtests.pro
    #- git clone https://github.com/benlau/asyncfuture.git
    #- ./run-test.sh "AsyncFuture" `pwd`/asyncfuture/tests/asyncfutureunittests/asyncfutureunittests.pro
    #- git clone https://github.com/benlau/quickflux.git
    #- ./run-test.sh "QuickFlux" $PWD/`find quickflux/tests -name *.pro`
    #- git clone https://github.com/benlau/sparkqml.git
    #- ./run-test.sh "SparkQML" $PWD/`find sparkqml/tests/sparkqmltests -name *.pro`
    - cat result.json
    - node logger/upload.js ${TARGET_NAME}

