language : cpp
dist: trusty
env:
  - DISPLAY=:99.0 TARGET_NAME="Qt 5.11" TARGET_PACKAGE="qt.511.gcc_64"
addons:
  apt:
    packages:
    - valgrind
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - (cd logger;npm install)
    - sh -e /etc/init.d/xvfb start
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - wget -q https://download.qt.io/archive/online_installers/3.0/qt-unified-linux-x64-3.0.1-online.run
    - export QT_CI_PACKAGES=${TARGET_PACKAGE} 
    - echo $QT_CI_PACKAGES
    - extract-qt-installer qt-unified-linux-x64-3.0.1-online.run `pwd`/Qt
    - QT_HOME=$PWD/`find Qt -name gcc_64`
    - export PATH=${QT_HOME}/bin:$PATH
    - ls Qt
    - find Qt -name "qmake"
    - echo $PATH
    - node logger/create.js $PWD/Qt/components.xml "${TARGET_NAME}" "${TARGET_PACKAGE}"
    - which qmake
    - qmake --version
    - ./run-test.sh "QTBUG-49370 - Use Singleton object from other Singleton object within the same package will hang" $PWD/qtbug-49370/qtbug-49370.pro
    - ./run-test.sh "QTBUG-56935  QQmlEngine crashing when trying to clear the component cache " $PWD/qtbug-56935/qtbug-56935.pro
    - ./run-test.sh "QTBUG-57545 The result of Array.sort() is incorrect if shift() was called" $PWD/qtbug-57545/qtbug-57545.pro
    - ./run-test.sh "QTBUG-57640 - Crash on loading Javascript file" $PWD/qtbug-57640/qtbug-57640.pro
    - ./run-test.sh "QTBUG-62666- JS `delete` operator leads to segfaults on garbage collecton" $PWD/qtbug-62666/qtbug-62666.pro

    - git clone https://github.com/benlau/qredux.git
    - ./run-test.sh "QRedux" `pwd`/qredux/tests/qreduxtests/qreduxtests.pro
    - git clone https://github.com/benlau/asyncfuture.git
    - ./run-test.sh "AsyncFuture" `pwd`/asyncfuture/tests/asyncfutureunittests/asyncfutureunittests.pro
    - git clone https://github.com/benlau/quickflux.git
    - ./run-test.sh "QuickFlux" $PWD/`find quickflux/tests -name *.pro`
    - git clone https://github.com/benlau/sparkqml.git
    - ./run-test.sh "SparkQML" $PWD/`find sparkqml/tests/sparkqmltests -name *.pro`
    - git clone https://github.com/e-fever/snapshottesting.git
    - ./run-test.sh "Library - SnapshotTesting" $PWD/`find snapshottesting/tests/snapshottestingunittests/ -name *.pro`
    - cat result.json
    - node logger/upload.js ${TARGET_NAME}

